apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: multi-tenancy-gitops
    group: pipeline
    type: git
  name: gitops-repo
data:
  branch: master
  host: github.com
  org: GitOps-CPs
  owner: GitOps-CPs
  parentdir: .
  protocol: https
  repo: multi-tenancy-gitops-apps
  url: https://github.com/GitOps-CPs/multi-tenancy-gitops-apps.git
